#!/usr/bin/env bash

VERSION=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)

rm -rf /tmp/release
mkdir -p /tmp/release
cp target/release/pod-babashka-filewatcher /tmp/release

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-filewatcher-$VERSION-$PLATFORM-amd64.zip" pod-babashka-filewatcher

## cleanup

rm pod-babashka-filewatcher
