#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp target/release/pod-babashka-filewatcher /tmp/release

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-filewatcher-$VERSION-$BABASHKA_PLATFORM-amd64.zip" pod-babashka-filewatcher

## cleanup

rm pod-babashka-filewatcher
