# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  linux:
    docker:
      - image: circleci/rust
    working_directory: ~/repo
    environment:
      - PLATFORM: linux
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - restore_cache:
          keys:
            - linux-{{ checksum "Cargo.lock" }}-{{ checksum "deps.edn" }}
      - run:
          name: Install Clojure
          command: |
            sudo apt install -y wget gnupg software-properties-common
            wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
            sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
            sudo apt update -y
            sudo apt install adoptopenjdk-8-hotspot -y
            sudo script/install-clojure /usr/local
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y
      - run:
          name: Build binary
          command: |
            cargo build --release
          no_output_timeout: 30m
      - run:
          name: Run tests
          command: |
            script/test
      - run:
          name: Release
          command: |
            .circleci/script/release
      - save_cache:
          paths:
            - ~/.m2
            - target
            - /usr/local/cargo/registry
          key: linux-{{ checksum "Cargo.lock" }}-{{ checksum "deps.edn" }}
      - store_artifacts:
          path: /tmp/release
          destination: release
  mac:
    macos:
      xcode: "12.0.0"
    environment:
      PLATFORM: macos # used in release script
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - restore_cache:
          keys:
            - mac-{{ checksum "Cargo.lock" }}-{{ checksum "deps.edn" }}
      - run:
          name: Install rustup
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y
      - run:
          name: Install Clojure
          command: |
            sudo script/install-clojure /usr/local
      - run:
          name: Build binary
          command: |
            cargo build --release
          no_output_timeout: 30m
      - run:
          name: Run tests
          command: |
            script/test
      - run:
          name: Release
          command: |
            .circleci/script/release
      - save_cache:
          paths:
            - ~/.m2
            - target
            - /usr/local/cargo/registry
          key: mac-{{ checksum "Cargo.lock" }}-{{ checksum "deps.edn" }}
      - store_artifacts:
          path: /tmp/release
          destination: release

workflows:
  version: 2
  ci:
    jobs:
      - linux
      - mac
